export enum Checkout {
  NAV_DIV = '.col-sm-8',
  NAV_UL = '.navbar-nav',
  PRODUCTS_LINK = 'Products',
  PRODUCT_LIST_DIV = '.features_items',
  VIEW_PRODUCT_LINK = 'View Product',
  ITEM_QUANTITY_TEXTBOX = '#quantity',
  ADD_TO_CART_BUTTON = 'Add to cart',
  MODAL_DIV = '.modal-content',
  VIEW_CART_LINK = 'View Cart',
  PROCEED_TO_CHECKOUT_BUTTON = 'Proceed To Checkout',
  REGISTER_LOGIN_LINK = 'Register / Login',
  CART_LINK = 'Cart',
  LOGOUT_LINK = 'Logout',
  CART_DESCRIPTION = '.cart_description',
  CART_PRICE = '.cart_price',
  CART_QUANTITY = '.cart_quantity',
  CART_TOTAL = '.cart_total_price',
  PLACE_ORDER_BUTTON = 'Place Order',
  NAME_ON_CARD_TEXTBOX = '[data-qa="name-on-card"]',
  CARD_NUMBER_TEXTBOX = '[data-qa="card-number"]',
  CVC_TEXTBOX = '[data-qa="cvc"]',
  EXPIRY_MONTH_TEXTBOX = '[data-qa="expiry-month"]',
  EXPIRY_YEAR_TEXTBOX = '[data-qa="expiry-year"]',
  PAY_BUTTON = '[data-qa="pay-button"]',
  EMPTY_CART_DIV = '#empty_cart',
}
