export enum SignUp {
  SIGN_UP_NAME_TEXTBOX = '[data-qa="signup-name"]',
  SIGN_UP_EMAIL_TEXTBOX = '[data-qa="signup-email"]',
  SIGN_UP_BUTTON = '[data-qa="signup-button"]',
  EMAIL_TEXTBOX = '[data-qa="email"]',
  PASSWORD_TEXTBOX = '[data-qa="password"]',
  FIRST_NAME_TEXBOX = '[data-qa="first_name"]',
  LAST_NAME_TEXTBOX = '[data-qa="last_name"]',
  NEWSLETTER_CHECKBOX = '#newsletter',
  ADDRESS_TEXTBOX = '[data-qa="address"]',
  COUNTRY_DROPDOWN = '[data-qa="country"]',
  STATE_TEXTBOX = '[data-qa="state"]',
  CITY_TEXTBOX = '[data-qa="city"]',
  ZIPCODE_TEXTBOX = '[data-qa="zipcode"]',
  MOBILE_TEXTBOX = '[data-qa="mobile_number"]',
  CREATE_ACCOUNT_BUTTON = '[data-qa="create-account"]',
  CONTINUE_BUTTON = '[data-qa="continue-button"]',
}
